[build]
builder = "DOCKERFILE"
watchPatterns = ["/services/grafana_agent"]

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3