[build]
builder = "DOCKERFILE"
buildCommand = "null"
watchPatterns = ["/services/grafana_agent"]

[deploy]
startCommand = "null"
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronSchedule = "null"