[build]
builder = "DOCKERFILE"
watchPatterns = ["/services/grafana"]

[deploy]
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3