[build]
builder = "DOCKERFILE"
watchPatterns = ["/Acsp-Backend"]

[deploy]
numReplicas = 1
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3