[build]
builder = "DOCKERFILE"
buildCommand = "null"
watchPatterns = ["/Acsp-Backend"]

[deploy]
startCommand = "null"
numReplicas = 1
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronSchedule = "null"