[build]
builder = "DOCKERFILE"
dockerfilePath = "/Acsp-Backend/Dockerfile"
watchPatterns = ["/Acsp-Backend"]

[deploy]
numReplicas = 1
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3