[build]
builder = "DOCKERFILE"
buildCommand = ""
watchPatterns = ["/Acsp-Backend"]

[deploy]
startCommand = ""
numReplicas = 1
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronSchedule = ""