[build]
builder = "DOCKERFILE"
watchPatterns = ["/services/prometheus"]

[deploy]
numReplicas = 1
healthcheckPath = "/api/v1/status/runtimeinfo"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3