app:
  security:
    actuator:
      username: "actuator"
      password: ${ACTUATOR_PASSWORD}
    prometheus:
      username: "prometheus"
      password: ${PROMETHEUS_PASSWORD}
  services:
    backend-url: ${ACSP_BACKEND_URL}
  config:
    environment: ${BOT_ENVIRONMENT}
    client-id: ${BOT_CLIENT_ID}
    client-secret: ${BOT_CLIENT_SECRET}
    bot-token: ${BOT_TOKEN}
    deployment-id: ${RAILWAY_DEPLOYMENT_ID}
    layout:
      test:
        id: 1170398575302295663
        roles:
          everyone: 1170398575302295663
          bot: 1170398575302295664
          member: 1170398575302295665
          team: 1170398575302295666
          admin: 1170398575302295667
        channels:
          welcome: 1170398577722404916
          rules: 1170398577722404917
          begin: 1170398577722404919
          team-chat: 1170398577722404921
          audit-log: 1170398577722404922
          admin-chat: 1170398577722404924
      prod:
        id: 1073266273619816549
        roles:
          everyone: 1073266273619816549
          bot: 1073678363237027915
          member: 1170390546188083200
          team: 1170381913635168507
          admin: 1073273895395791009
        channels:
          welcome: 1073275189338591233
          rules: 1073273398693724332
          begin: 1073346501314629732
          team-chat: 1170387449885765682
          audit-log: 1170387921463955546
          admin-chat: 1073273398693724333
    definition:
      command-prefix: "!"
      messages:
        - label: "error"
          message:
            embeds:
              - author:
                  name: "$error.author.name$"
                  icon_url: "https://cdn-icons-png.flaticon.com/512/2569/2569174.png"
                title: "$0"
                description: "$1"
                color: "#202225"
                footer:
                  text: "$footer.text.2$" # contains $2
                  timestamp: "$3"
                  icon-url: "https://cdn.discordapp.com/avatars/1220705902622150666/71317fc3ccdc919c1a47d078161fc4f0.webp?size=256"
        - label: "internal-error"
          message:
            embeds:
              - author:
                  name: "$error.author.name$"
                  icon_url: "https://cdn-icons-png.flaticon.com/512/2569/2569174.png"
                title: "$error.internal.title$"
                description: "$error.internal.description$" # contains $0
                color: "#202225"
                footer:
                  text: "$footer.text.1$" # contains $1
                  timestamp: "$2"
                  icon-url: "https://cdn.discordapp.com/avatars/1220705902622150666/71317fc3ccdc919c1a47d078161fc4f0.webp?size=256"
        - label: "argument-validation-report"
          message:
            embeds:
              - author:
                  name: "$error.author.name$"
                  icon-url: "https://cdn-icons-png.flaticon.com/512/2569/2569174.png"
                title: "$error.argument_validation_report.title$"
                description: "$error.argument_validation_report.description$" # contains $0
                color: "#202225"
                fields: [] # see field "argument-validation.error"
                footer:
                  text: "$footer.text.1$" # contains $1
                  timestamp: "$2"
                  icon-url: "https://cdn.discordapp.com/avatars/1220705902622150666/71317fc3ccdc919c1a47d078161fc4f0.webp?size=256"
      commands:
        - name: "help"
          enabled: true
          description: "$command.help.description$"
          subcommands:
            available: false
            required: false
          arguments:
            - id: "command"
              type: string
              description: "$command.help.argument.command.description$"
              required: false
          permissions:
            - channels:
                - type: all
              roles:
                - type: simple
                  role: everyone
      fields:
        - label: "argument-validation.error"
          field:
            name: "Argument $0"
            value: "$1"
            inline: false
spring:
  application:
    name: ACSP Bot
  output:
    ansi:
      enabled: always
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, bot, externalServices
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'prometheus' ]
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      service: ${RAILWAY_SERVICE_NAME}
      environment: ${RAILWAY_ENVIRONMENT_NAME}
  info:
    java:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
info:
  railway:
    project_name: ${RAILWAY_PROJECT_NAME}
    environment_name: ${RAILWAY_ENVIRONMENT_NAME}
    service_name: ${RAILWAY_SERVICE_NAME}
    service_url: ${RAILWAY_PUBLIC_DOMAIN}
    replica_id: ${RAILWAY_REPLICA_ID}
    deployment_id: ${RAILWAY_DEPLOYMENT_ID}
server:
  port: 8081
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: off
logging:
  level:
    org.springframework.boot.web.embedded: OFF
    org.springframework.boot.web.servlet.context: OFF
    org.apache.catalina: OFF