apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://acsp-prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: agent_user
    secureJsonData:
      basicAuthPassword: $GRAFANA_AGENT_TOKEN