apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: ACSP Database
    orgId: 1
  - name: Auth Database
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://acsp-prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: agent_user
    secureJsonData:
      basicAuthPassword: $GRAFANA_AGENT_TOKEN
  - name: ACSP Database
    type: postgres
    url: $ACSP_DB_HOST:$ACSP_DB_PORT
    user: $ACSP_DB_USER
    secureJsonData:
      password: $ACSP_DB_PASSWORD
    jsonData:
      database: $ACSP_DB_NAME
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 10
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
  - name: Auth Database
    type: postgres
    url: $AUTH_DB_HOST:$AUTH_DB_PORT
    user: $AUTH_DB_USER
    secureJsonData:
      password: $AUTH_DB_PASSWORD
    jsonData:
      database: $AUTH_DB_NAME
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 10
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false