[build]
builder = "DOCKERFILE"
buildCommand = "null"
watchPatterns = ["/services/prometheus"]

[deploy]
startCommand = "null"
numReplicas = 1
healthcheckPath = "/hello"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronSchedule = "null"