[build]
builder = "DOCKERFILE"
watchPatterns = ["/services/supertokens"]

[deploy]
numReplicas = 1
healthcheckPath = "/hello"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3