[build]
builder = "DOCKERFILE"
buildCommand = ""
watchPatterns = ["/services/prometheus"]

[deploy]
startCommand = ""
numReplicas = 1
healthcheckPath = "/hello"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronSchedule = ""