app:
  security:
    actuator:
      username: "actuator"
      password: ${ACTUATOR_PASSWORD}
    prometheus:
      username: "prometheus"
      password: ${PROMETHEUS_PASSWORD}
  services:
    auth-api-key: ${AUTH_API_KEY}
    supertokens-url: ${ACSP_SUPERTOKENS_URL}
    bot-url: ${ACSP_BOT_URL}
spring:
  application:
    name: ACSP Backend
  datasource:
    url: jdbc:postgresql://${ACSP_DB_HOST}:${ACSP_DB_PORT}/${ACSP_DB_NAME}
    username: ${ACSP_DB_USER}
    password: ${ACSP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: -1
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${ACSP_SUPERTOKENS_URL}/appid-public/.well-known/jwks.json"
  output:
    ansi:
      enabled: always
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, externalServices
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'prometheus' ]
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      service: ${RAILWAY_SERVICE_NAME}
      environment: ${RAILWAY_ENVIRONMENT_NAME}
  info:
    java:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
info:
  railway:
    project_name: ${RAILWAY_PROJECT_NAME}
    environment_name: ${RAILWAY_ENVIRONMENT_NAME}
    service_name: ${RAILWAY_SERVICE_NAME}
    service_url: ${RAILWAY_PUBLIC_DOMAIN}
    replica_id: ${RAILWAY_REPLICA_ID}
    deployment_id: ${RAILWAY_DEPLOYMENT_ID}
server:
  port: 8080
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: off
  tomcat:
    threads:
      min-spare: 4
      max: 16
  jetty:
    threads:
      min: 4
      max: 16
logging:
  level:
    org.springframework.boot.web.embedded: ERROR
    org.springframework.boot.web.servlet.context: ERROR
    org.springframework.boot.devtools: ERROR
    org.apache.catalina: ERROR